### ISSUE TITLE
Need backreference to usbhid driver from the disconnect issue

### ISSUE THREAD

**Issue by sriemer** [sriemer/fix-linux-mouse#10]
From the GitHub traffic graph I know that this howto has been referenced from:
http://linet.gr.jp/~kojima/PlamoWeb/ML/htdocs/201808/msg00019.html

They only looked at the mouse disconnect issue and not at the usbhid kernel driver explanation. So they didn't know that `0x00000400` is `HID_QUIRK_ALWAYS_POLL`. So that one should be mentioned there as well and a backreference to the usbhid explanation should be added.

But it is interesting that there is also a PixArt OEM mouse from Microsoft.

**Comment by sriemer** [comment]
@tenforward: Did I get that right that `HID_QUIRK_ALWAYS_POLL` works for the PixArt OEM mouse from Microsoft? TIA

Patch sent to linux-usb mailing list: https://marc.info/?l=linux-usb&m=154159427814212&w=2

**Comment by sriemer** [comment]
@kkzst: Same question to you. TIA

**Comment by kkzst** [comment]
The OP wrote that HID_QUIRK_ALWAYS_POLL works for his mouse, though I have not tried yet.   In my post to the ML,  I wrote that 0x400 instructs the driver polling instead of waiting interrupts, and that it is explained in your howto.  So some members of the ML likely know that 0x400 is HID_QUIRK_ALWAYS_POLL, I guess.

**Comment by sriemer** [comment]
Perfect, thanks!

**Comment by kkzst** [comment]
Thanks too, for your effort to maintain this helpful howto.

**Comment by sriemer** [comment]
The upstream maintainer (my colleague jikos) applied the patch.
So this will be fixed for all Linux distros soon. :tada: 

**For contributors** in future: If you find out that a quirk fixes a USB mouse, then please open a GitHub issue here so that we can discuss and create a patch for upstream inclusion. TIA

This particular device has issues **since 5 years** already. I'm glad that this howto was able to locate the problem of another device.

Contributions are always welcome. I've intentionally chosen GitHub for SEO to fight unstructured unresolved forum posts the web is spammed with and to fight blog posts which prevent comments/discussion and modification after some time. The more changes and contribution the higher the Google ranking. My advantage is the direct connection to my SUSE colleagues who work in this area.

Related commit: 65d31a91f541268cf9cb50017494584d717543b1
