### ISSUE TITLE
Taking apart Dell MS116t PixArt mouse

### ISSUE THREAD

**Issue by sriemer** [sriemer/fix-linux-mouse#16]
I used that device a lot. Dell were able to set their own USB IDs and the device has 1000 CPI.
So which PixArt Imaging IC is inside?

It is the **PAW3515DB-VJZA**.

Datasheet: https://cdn.datasheetspdf.com/pdf-down/P/A/W/PAW3515DB-PixArt.pdf

In contrast to the PAN3511, the USB mouse controller part has no detailed description any more. But the USB IDs are programmable in this one for sure. <br/>**Update:** The link points now to the full datasheet.

There are two screws at the bottom back beneath the rubber slider. Then you have to lift the top casing and push it above the cable towards you simultaneously to get it out of the plastic latches in the front.

**Comment by sriemer** [comment]
![a94b2f51-a176-47dd-be4b-eab03143dd4f](https://user-images.githubusercontent.com/1803210/52278542-93330a00-2957-11e9-8d25-4cdf7d99e176.jpeg)
![0f96778c-4533-4786-8b3e-9c793bb6cdca](https://user-images.githubusercontent.com/1803210/52278543-93330a00-2957-11e9-96c7-9af164f1ec40.jpeg)
![997824a5-97e6-4b97-bcfb-ce8ef0c4308e](https://user-images.githubusercontent.com/1803210/52278544-93cba080-2957-11e9-87ec-8315c7a6b6ec.jpeg)
![46c242cf-1adc-4631-8140-0db8e1bc7d18](https://user-images.githubusercontent.com/1803210/52278545-93cba080-2957-11e9-9e48-6b76061d8568.jpeg)

**Comment by sriemer** [comment]
USB IDs: `413c:301a`

Mouse connected to the system:
```
[ 8127.560093] usb 3-3: new low-speed USB device number 6 using xhci_hcd
[ 8127.691991] usb 3-3: New USB device found, idVendor=413c, idProduct=301a
[ 8127.691996] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 8127.691999] usb 3-3: Product: Dell MS116 USB Optical Mouse
[ 8127.692014] usb 3-3: Manufacturer: PixArt
[ 8127.694222] input: PixArt Dell MS116 USB Optical Mouse as /devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3:1.0/0003:413C:301A.0008/input/input13
[ 8127.694546] hid-generic 0003:413C:301A.0008: input,hidraw3: USB HID v1.11 Mouse [PixArt Dell MS116 USB Optical Mouse] on usb-0000:00:14.0-3/input0
```

**Comment by rik26** [comment]
Thank you for your disassembly tutorial !

**Comment by sriemer** [comment]
There is a new video regarding this. But the guy in the video doesn't seem to be experienced with it. He plain needs too much time, doesn't explain, does not use the right trick to get the casing out of the plastic latches: https://www.youtube.com/watch?v=6WBQ1ihy3m0

**Comment by sriemer** [comment]
An even newer video - guy with experience: https://www.youtube.com/watch?v=8ygFQR5jslc.
He opens an older **MS116p** which is a bit different inside.
