### ISSUE TITLE
Touchbar doesn't work if an external USB HID device is connected.

### ISSUE THREAD

**Issue by AdityaGarg8** [sriemer/fix-linux-mouse#26]
I have been facing a strange bug with the touchbar found on Apple Macs. If there are external USB HID devices connected to the Mac during boot, it fails to work. Else, it works well. Also, after boot if I plug in an external USB HID device, then the touchbar isn't affected. Can you help me in this issue.

**Comment by sriemer** [comment]
Sorry, got no Mac. Needs to be reported to them. As a Mac customer you have support from Apple. Sounds like a software bug.
